// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/login.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/register': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/register.post').default>>>>
    }
    '/api/painel/appointments/:id': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/appointments/[id].put').default>>>>
    }
    '/api/painel/appointments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/appointments/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/appointments/index.post').default>>>>
    }
    '/api/painel/clients': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/clients/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/clients/index.post').default>>>>
    }
    '/api/painel/dashboard/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/dashboard/stats.get').default>>>>
    }
    '/api/painel/link-bio': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/link-bio/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/link-bio/index.post').default>>>>
    }
    '/api/painel/loyalty': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/loyalty/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/loyalty/index.post').default>>>>
    }
    '/api/painel/professionals/:id': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/professionals/[id].put').default>>>>
    }
    '/api/painel/professionals': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/professionals/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/professionals/index.post').default>>>>
    }
    '/api/painel/queue/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/queue/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/queue/[id].put').default>>>>
    }
    '/api/painel/queue': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/queue/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/queue/index.post').default>>>>
    }
    '/api/painel/reviews/:id': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/reviews/[id].put').default>>>>
    }
    '/api/painel/reviews': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/reviews/index.get').default>>>>
    }
    '/api/painel/salon/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/salon/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/salon/[id].put').default>>>>
    }
    '/api/painel/salon': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/salon/index.post').default>>>>
    }
    '/api/painel/salon/my': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/salon/my.get').default>>>>
    }
    '/api/painel/services/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/services/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/services/[id].put').default>>>>
    }
    '/api/painel/services': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/services/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/services/index.post').default>>>>
    }
    '/api/painel/transactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/transactions/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/painel/transactions/index.post').default>>>>
    }
    '/api/salao/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/salao/[slug].get').default>>>>
    }
    '/api/salons': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/salons/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/image/dist/runtime/ipx').default>>>>
    }
  }
}
export {}